### PR TITLE
Make timestamp link use dotted underline to be more obvious

### PR DESCRIPTION
**Pull request by troy**
Verified and examined in Gmail.

### CODE REVIEW

**Comment by troy** [comment]
@rpheath giving to you to bless or adjust as you see fit

**Comment by rpheath** [comment]
@troy the inline style looks a-okay to me, but do you happen to have that email handy to forward on? Just curious of the output.

**Comment by troy** [comment]
Sure. Here's an example surrounded by events showing the current behavior. Looking at it more, I propose this change plus retaining the existing underline when the user hovers over the timestamp. Thoughts? If that works, would you like to implement it? It's pretty easy to test by using DOM inspector on an alert email from production, which is what I did here.

example

**Comment by rpheath** [comment]
@troy I mentioned in Slack, that if we're going to change the underline treatment, I kind of like `dashed` better than `dotted`. Here's what `dashed` looks like:



However, another question I had was whether or not we should change the link style at all? If your concern is obviousness, then I might propose just letting it be the traditional blue link like the rest of the links in the email.

Thoughts?

**Comment by troy** [comment]
> @troy I mentioned in Slack, that if we're going to change the underline treatment, I kind of like dashed better than dotted. Here's what dashed looks like:

Makes sense to me.

> However, another question I had was whether or not we should change the link style at all? If your concern is obviousness, then I might propose just letting it be the traditional blue link like the rest of the links in the email.

Valid point. I think a blue link on every line would be pretty distracting, though. IMO, blue makes sense when someone has no idea what text is a link and what isn't, but is overkill as a subtle hint. What do you think?

**Comment by rpheath** [comment]
@troy yeah, I agree. Giving it back to you.

**Comment by troy** [comment]
@rpheath check this out:

a

I think dashed gets in the way too :( Thoughts?

**Comment by rpheath** [comment]
Hmm… Yeah, seeing several does make a bigger difference. Then my vote would go to either the dotted or solid (how it was).

**Pull request closed without merging**
