### PR TITLE
Added Mattermost Integration

### PR DESCRIPTION
**Pull request by cduverne**
This is a first attempt at creating a Mattermost Integration service.
It's mainly based on Slack integration for now.

### CODE REVIEW

**Comment by johlym** [comment]
Hi @cduverne this is awesome! :)

The tests are going to fail so long as https://github.com/cduverne/papertrail-services/blob/506fceb3b06f7fce726a74ed10a10ab4647550ec/services/mattermost.rb#L2 isn't named properly. I suspect it should be `Service::Matermost` not `Service::Slack`?

**Comment by cduverne** [comment]
Thanks @johlym !

I replaced all old ref to slack.
I'm completely new to this testing chain, do you have guidelines to stub the tests ?

**Comment by johlym** [comment]
Awesome @cduverne! ☕ 

Although not necessarily easy, what comes to mind would be to replicate the functionality this integration provides. The less than easy part about that idea is there isn't a service to test against since Mattermost is self-hosted only. If you have an instance that can be tested against, you'll have the best opportunity to write valuable tests.

**Comment by cduverne** [comment]
Thanks @johlym !

How can I test it ? :) 
At large, what do I have to do to run the code ? bundle install ? And ?

Thanks

**Comment by johlym** [comment]
Hi @cduverne!

As long as you have properly structured tests in `/test`, running `rake test` will run all the tests in the folder and `rake test TEST=path_to_test_file` lets you isolate. In this case `rake test TEST=test/mattermost_test.rb` will only run the tests in that file. 

The tests will also likely fail so long as the endpoints aren't live (like [this one](https://github.com/cduverne/papertrail-services/blob/255b18f3ad667ee40bda16479be96e86a6e19f68/test/mattermost_test.rb#L5)).

**Comment by cduverne** [comment]
Ok, I manage to have it running.

How can I get a live endpoint ? I tried to use my own instance to post to within http_stubs.post, but it's only taking into account the last /hooks/... part.

**Comment by johlym** [comment]
@cduverne Looks like you got it figured out. Awesome :)

**Comment by cduverne** [comment]
This version has been cleaned.

The part about message truncation, which was taken from Slack integration doesn't to be applicable to Mattermost. (Still to be tested)

When do you think this could be implemented in the UI ?

**Comment by cduverne** [comment]
Hello !!! 

Any news ?

**Comment by cduverne** [comment]
Hello ? 

Any news ?

**Comment by johlym** [comment]
Hey @cduverne I'll try to get this taken care of this week.

**Comment by cduverne** [comment]
Great !!! Thanks Jonathan !

Le mar. 5 juil. 2016 20:57, Johnathan Lyman <notifications@github.com> a
écrit :

> Hey @cduverne <https://github.com/cduverne> I'll try to get this taken
> care of this week.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/papertrail/papertrail-services/pull/77#issuecomment-230570156>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABZAZEZADj_H1RDwGoVFhBbmWGlNhz46ks5qSqk2gaJpZM4IxDqq>
> .
>
-- 

Cyrille Duverne
Consultant - Architect
EURA NOVA

Tel : +32 (0) 493 253 263

-- 
♻ Be green, keep it on the screen

**Comment by cduverne** [comment]
Hello !

Following our discussion with @leonsodhi , here is the result of the embedded tests toward our Mattermost instance :) 

Thanks
Cyrille

test-papertrail-mattermost

**Comment by johlym** [comment]
@leonsodhi @troy any input before I make this a thing?

**Comment by troy** [comment]
Looks good here. 👍

**Comment by cduverne** [comment]
Yes ! Cool !

Le jeu. 7 juil. 2016 23:26, Troy Davis <notifications@github.com> a écrit :

> Looks good here. 👍
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/papertrail/papertrail-services/pull/77#issuecomment-231212336>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABZAZP3JAk5bHBaRj6ITKAfOpnR6igj4ks5qTW8OgaJpZM4IxDqq>
> .
>
-- 

Cyrille Duverne
Consultant - Architect
EURA NOVA

Tel : +32 (0) 493 253 263

-- 
♻ Be green, keep it on the screen

**Comment by johlym** [comment]
Done.

**Pull request merged**
